kind = "web"
previewPath = "/"
title = "Royal Dental Centre"
version = "1.0.0"
id = "artifacts/dental-clinic"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23961

[services.development]
run = "pnpm --filter @workspace/dental-clinic run dev"

[services.env]
PORT = "23961"
BASE_PATH = "/"
