kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.build]
args = ["sh", "-c", "pnpm --filter @workspace/dental-clinic run build && pnpm --filter @workspace/api-server run build"]

[services.production.build.env]
NODE_ENV = "production"
BASE_PATH = "/"

[services.production.run]
args = ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/healthz"
